name: Continuous Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install NPM packages
        run: npm ci
      # Ordered from most to least severe/fix order.
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm install @vitest/coverage-v8@latest && npm test
      - name: Run lint
        run: npm run lint
      - name: Run Typescript checks
        run: npm run tsc
      - name: Run Vue+Typescript checks
        run: npm run vue-tsc
      - name: Run formatting check
        run: npm run formatcheck

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
